---

stats:
  class: Stats

#make:
#  class: Autotools

test:
  class: TestUnit

notes:
  class: Notes

rdoc:
  class: RDoc
  template: jamis
  inline: true

ridoc:
  class: RIDoc

gem:
  class: Gem

rubyforge:
  class: Rubyforge


#resources:
#
#  rubyforge:
#    class: Rubyforge
#    # new options
#
#actions:
#
#  publish:
#    - resource: rubyforge
#      action: publish
#      srcdir: admin/web
#
#    - resource: rubyforge
#      action: publish
#      source: doc/rdoc
#      subdir: rdoc

